### ISSUE TITLE
light speed

### ISSUE THREAD

**Issue by rmsrosa** [sostock/UnitfulEquivalences.jl#5]
Hi,

Why do you need to define `c²` for
```julia
const c² = Quantity(convert(Int64, ustrip(c0)), unit(c0))^2

@eqrelation MassEnergy Energy/Mass = c²
```
instead of just using directly `c0^2`:
```julia
@eqrelation MassEnergy Energy/Mass = c0^2
```
?

**Comment by sostock** [comment]
`Unitful.c0` is based on an `Int`, which means `Int32` on 32-bit systems, so `c0^2` would overflow on those systems. Therefore, it is converted to `Int64`.

**Comment by rmsrosa** [comment]
I see. Thanks!
